### ISSUE TITLE
Onboard Isla

### ISSUE THREAD

**Issue by GeorgiaHCA** [GeorgiaHCA/AutSPACEs#80]
### Summary

Onboard Isla

### Deadline 

Friday 19th Feb 2021

### What needs to be done?

- [x]  Introduce to project
- [x]  Add to repo and make sure has links
- [x] Connect to community 

### Who can help?

Everyone welcome Isla :)

**Comment by Islast** [comment]
:) :wave:

**Comment by GeorgiaHCA** [comment]
Hey @Islast :D
