### ISSUE TITLE
How do I start contributing to this project as an aspiring GSoC student?

### ISSUE THREAD

**Issue by kkothari2001** [GeorgiaHCA/AutSPACEs#85]
Apologies if this isn't the best place to ask this doubt. But what would be the best place to start understanding this repo better and start contributing to it? I tried to join the slack link in the README, but that doesn't seem to be working!

I would love to start contributing to this repo as soon as possible!

**Comment by GeorgiaHCA** [comment]
Hi, thanks for your comment! Yes, this iis a great place to ask. 

You can use this link to join our slack channel: https://slackin.openhumans.org

I see we have the wrong link in the README! II'll update it right away. 

Welcome - delighted you'd like to contribute ⭐
